%include	/usr/lib/rpm/macros.perl
Summary:	Simple vector graphics creator (with stdin/out interface)
Summary(pl.UTF-8):	Prosty program do grafiki wektorowej (z interfejsem stdin/out)
Name:		drawtool
Version:	3.2.2
Release:	6
License:	GPL
Group:		X11/Applications/Graphics
Source0:	http://www.earth.li/projectpurple/files/%{name}-%{version}.tar.gz
# Source0-md5:	97ffd36c555d67f58fa50615afc28772
Patch0:		%{name}-makefile.patch
Patch1:		%{name}-build.patch
URL:		http://www.earth.li/projectpurple/progs/drawtool.html
BuildRequires:	gtk+-devel
BuildRequires:	imlib-devel
BuildRequires:	netpbm-devel
BuildRequires:	perl-devel >= 1:5.6.1
BuildRequires:	rpm-perlprov >= 4.1-13
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Drawtool is a simple application that reads in simple vector geometry
from stdin and displays it in a GTK+ window. Similarly, it will write
data onto stdout as generated by click-drag mouse movements. It can
output to bitmap files and Postscript. It can be used as a general
purpose drawing program, a network whiteboard, a picture viewer or a
scrapbook for quickly getting down ideas....

%description -l pl.UTF-8
Drawtool jest prostą aplikacją która wczytuje opis prostej grafiki
wektorowej ze standardowego wejścia i wyświetla ją w okienku GTK+.
Analogicznie, wypisuje on dane na standardowe wyjście w miarę jak
obraz jest generowany za pomocą myszki i użytkownika. Wyjście może też
być generowane w formie bitmapy lib Postscriptu. Drawtool może być
używany jako wszechstronny program do rysunków, sieciowy "whiteboard",
przeglądarka obrazków, notatnik do szybkiego zapisywania pomysłów...

%package perl
Summary:	Perl extensions for drawtool
Summary(pl.UTF-8):	Perlowe rozszerzenia dla drawtoola
Group:		X11/Applications/Graphics

%description perl
Perl extensions for drawtool: PSDrawtool, SVGDrawtool and perltool.

%description perl -l pl.UTF-8
Perlowe rozszerzenia dla drawtoola: PSDrawtool, SVGDrawtool i
perltool.

%prep
%setup -q
%patch0 -p1
%patch1 -p1

%build
%{__make} \
	CC="%{__cc}" \
	CFLAGS="%{rpmcflags}"

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_bindir},%{_mandir}/man1}

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT \
	MANDIR=%{_mandir}/man1 \
	BINDIR=%{_bindir}

mv -f logo/utils logo-utils

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc TODO README CHANGES docs/drawtool.pdf utils logo-utils
%attr(755,root,root) %{_bindir}/logo
%attr(755,root,root) %{_bindir}/drawtool
%{_mandir}/man*/*

%files perl
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/*.pl
